job:
    script:
        - mysql --user rfamro --host mysql-rfam-public.ebi.ac.uk --port 4497 --database Rfam
        - cp $CI_PROJECT_DIR/* /tmp
        - bash /tmp/script
    only:
        - merge_requests
